# Generated by Django 2.2.3 on 2020-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taskmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_task', models.CharField(max_length=100)),
                ('task_category', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('repeatative_task', models.BooleanField()),
                ('task_status', models.CharField(max_length=100)),
            ],
        ),
    ]
