# Generated by Django 2.2.3 on 2020-01-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taskmodel',
            new_name='Taskinfo',
        ),
    ]
