# Generated by Django 2.2.3 on 2020-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0006_auto_20200219_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='repeatative_task',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='task_status',
            field=models.CharField(choices=[('notstarted', 'New'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='notstarted', max_length=100),
        ),
    ]
