# Generated by Django 2.2.3 on 2020-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0009_auto_20200223_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='task_status',
            field=models.CharField(max_length=100),
        ),
    ]
