# Generated by Django 2.2.3 on 2020-02-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0010_auto_20200223_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='user_task',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='taskinfo',
            old_name='repeatative_task',
            new_name='task_repeatative',
        ),
    ]
