# Generated by Django 2.2.3 on 2020-03-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0011_auto_20200227_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='task_repeatative',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
    ]
